### ISSUE TITLE
Explore how we structure package.json in the monorepo - what is best practice?

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms-v2#11]
> @Jbithell according to this [answer](https://stackoverflow.com/a/56254478) it should be committed. But will required to be updated. I would keep it as such. May need updating commands with `npm ci`

`package-lock.json` has huge value and we keep all three of them in source control for each of the three projects in this repo - I'm just suggesting that maintaining a 4th that duplicates the three of them is extra work that most of us will forget to do (as the existence of your PR demonstrates!) especially given it isn't really used by anyone/anything except one or two of the contributors who prefer it over using the individual `package.json` files in each of three folders in the monorepo.

_Originally posted by @Jbithell in https://github.com/bstudios/adam-rms/issues/256#issuecomment-995060161_

**Comment by chriscn** [comment]
Closing this since project is just using APP
