### ISSUE TITLE
[FEATURE] Test external links in assets and CMS pages

### ISSUE THREAD

**Issue by Robert-Watts** [adam-rms/adam-rms-v2#16]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is the potential that external links are not going to work on android and ios. In this case we need to use a in app browser ([https://capacitorjs.com/docs/apis/browser](https://capacitorjs.com/docs/apis/browser)).

**If stuff is not broken just close the ticket.**

### Describe the solution you'd like

If stuff is broken, use a in app browser ([https://capacitorjs.com/docs/apis/browser](https://capacitorjs.com/docs/apis/browser)). **If stuff is not broken just close the ticket.**

**Comment by cherry-john** [comment]
If the links target "_system", they should open in the device's default browser. I've added that in [AssetType.tsx](https://github.com/adam-rms/adam-rms-v2/blob/main/app/src/pages/assets/AssetType.tsx)

**Comment by Robert-Watts** [comment]
Link put into CMS pages or into assets descriptions won't have that by
default will they?

**Comment by cherry-john** [comment]
I assume not, but not totally sure

**Comment by cherry-john** [comment]
Waiting on #66 and #65

**Comment by cherry-john** [comment]
Confirmed working on Android Build
