### ISSUE TITLE
[BUG] CMS pages crash if no pages found

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms-v2#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9b3e1406db4117705195e2b2b814514903c87002

### Current Behavior

CMS page list in sidebar menu doesn't have an error check, and so crashes if it doesn't have any information.
![image](https://user-images.githubusercontent.com/54247748/147872144-0c4cdd59-49a1-4127-8538-8c7c0b1d5c83.png)

### Expected Behavior

List of pages to disappear if there are no pages

### Steps To Reproduce

Run the 9b3e1406db4117705195e2b2b814514903c87002 , without an instance of v1 api running.
App will crash after a set time

### How are you accessing AdamRMS?

https://www.whatsmybrowser.org/b/ZDPOR

**Comment by Robert-Watts** [comment]
Forgot to test it with no pages...
