### ISSUE TITLE
Styling overhaul

### ISSUE THREAD

**Issue by cherry-john** [adam-rms/adam-rms-v2#21]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Once initial features have been finalised, the whole app will need a bit of a tidy and standardisation in terms of styling and components used.

**Comment by Robert-Watts** [comment]
As this is done are you looking at targeting pc and mobile at the same time?

**Comment by cherry-john** [comment]
Yeah, although at this stage, I think we're prioritising mobile

**Comment by cherry-john** [comment]
Duplicate of #28

**Comment by cherry-john** [comment]
Have refocused what #28 is so this is now relevant again 😇

**Comment by cherry-john** [comment]
Have refocused what #28 is so this is now relevant again 😇
